### ISSUE TITLE
ERROR mapreduce.GeoMesaRecordWriter

### ISSUE THREAD

**Issue by OSwoboda** [geomesa/geomesa-tutorials#3]
I'm following the mapreduce ingest tutorial and get error messages for every entry that is ingested. Here an example:

> ERROR mapreduce.GeoMesaRecordWriter: Error creating mutations from feature '209613f1-fefc-4d39-9ea2-228c8857dde2=501698408|2016-01-12T23:00:00.000Z|201601|2016|2016.0356|USAGOV|HILLARY CLINTON|USA|||||GOV|||USA|UNITED STATES|USA||||||||0|012|012|01|1|-0.4|1|1|1|-1.2931035|1|Russia|RS|RS|60.0|100.0|RS|3|Washington, District of Columbia, United States|US|USDC|38.8951|-77.0364|531871|1|Russia|RS|RS|60.0|100.0|RS|20160113|POINT (100 60)'
java.lang.ClassCastException

I'm using Java 8, hadoop 2.2.0 (2.2.2 doesn't exist), zookeper 3.4.8, accumulo 1.6.5/1.5.4 and geomesa 1.2.0.

**Comment by elahrvivaz** [comment]
Is there more to the error? There should be a stack trace that might help.
Thanks,

**Comment by OSwoboda** [comment]
There is nothing more, thats everything I see on my console. The ingest works but really slow because of the error message for each entry.

**Comment by elahrvivaz** [comment]
There might be more in the hadoop distributed logs, if you can check those. If the ingest is working, then only some of the lines are failing with that error. Likely the input data is not being validated correctly... I will see if anyone has time to check this out.
Thanks,

**Comment by mdzimmerman** [comment]
@OSwoboda - Thank you for reporting the error. Unfortunately we can't replicate your error, but  I have a couple of questions:
1) Are you using Accumulo 1.6.4 or 1.5.4?
2) Which GDELT records specifically are you trying to ingest? It looks like you're trying to ingest records from Jan 2016. That should be fine; I don't think that the GDELT file format changes much, but it might be useful to find the specific file that causes the problems.
3) Are any records successfully being ingested in the GeoMesa Accumulo tables? One of the issues with GDELT is that many GDELT records do not contain a valid lat/long, in some cases as many as 10%. GeoMesa will ignore and not ingest the "bad" records, but depending on your logging configuration it may possibly be printing out an error for each of the 10% of records that fail but may still be ingesting the other 90%..

**Comment by OSwoboda** [comment]
There are some stack traces at the beginning of the job, but I can't write them to file or something.

1) I'm running accumulo 1.6.5 currently but had the same issue with 1.5.4 before.
2) I'm trying to ingest 01/2016 but had the same issue with the files in the tutorial (2013/14)
3) The table is growing and I've done an mapreduce ingest with the 1.1.0 tutorial (geomesa-gdelt-1.0-SNAPSHOT.jar) and thats works fine, so it couldn't be the gdelt files.

**Comment by elahrvivaz** [comment]
I believe that we were just silently swallowing the errors in 1.1.x - so it might have been behaving the same, but you didn't realize it. If you still have the 1.1.x tables, you could compare the record counts in accumulo with the 1.2.0 tables (after compacting the tables, so that you get an accurate count).

**Comment by elahrvivaz** [comment]
@OSwoboda The error in that particular feature is due to the FractionDate:Float field having the value 'BUS'. It appears that feature builder tries to convert the values to the correct type (float), but if it can't convert it falls back to the original value. When we try to serialize the feature, we expect the field to be a float (as per the simple feature type), thus the exception.
I've created a gist that should fix the problem: https://gist.github.com/elahrvivaz/f16f71f6249162450982
You can try pasting that into the try/catch block in the gdelt ingest mapper here: https://github.com/geomesa/geomesa-tutorials/blob/master/geomesa-examples-gdelt/src/main/java/com/example/geomesa/gdelt/GDELTIngestMapper.java#L51-L65
Instead of setting the attributes in the feature builder (which doesn't ensure the conversion), it calls setAttribute on the feature - this ensures that the conversion takes place, otherwise the value will be null.
Let me know if that fixes the issue - if so, I'll put up a permanent fix.
Thanks,

**Comment by OSwoboda** [comment]
The Build failes:

> [ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/oli/Installs/geomesa-tutorials/geomesa-examples-gdelt/src/main/java/com/example/geomesa/gdelt/GDELTIngestMapper.java:[62,36] no suitable method found for setAttribute(java.lang.String)
    method org.opengis.feature.simple.SimpleFeature.setAttribute(java.lang.String,java.lang.Object) is not applicable
      (actual and formal argument lists differ in length)
    method org.opengis.feature.simple.SimpleFeature.setAttribute(org.opengis.feature.type.Name,java.lang.Object) is not applicable
      (actual and formal argument lists differ in length)
    method org.opengis.feature.simple.SimpleFeature.setAttribute(int,java.lang.Object) is not applicable
      (actual and formal argument lists differ in length)

**Comment by OSwoboda** [comment]
BTW: Would be nice to add the Attribute SOURCEURL(since April 2013) to the ingest.

**Comment by elahrvivaz** [comment]
sorry, there was a typo.
`simpleFeature.setAttribute(attributes[i]);`
needs to be
`simpleFeature.setAttribute(i, attributes[i]);`
I updated the gist with the full method signature and checked that it compiles.
Thanks,

**Comment by OSwoboda** [comment]
It's working now! Thank you!

**Comment by elahrvivaz** [comment]
@OSwoboda great, I'll push up the fix.
Thanks again,

**Comment by elahrvivaz** [comment]
pushed
