### ISSUE TITLE
Cassandra example with 1.3.1

### ISSUE THREAD

**Issue by ajayaks** [geomesa/geomesa-tutorials#47]
Hi, 

I was following below link for 1.3.0 as i didn't find the same info in release 1.3.1.
http://www.geomesa.org/documentation/user/cassandra/commandline_tools.html#.

There is some gap as below:-
1. --name-space is not available with geomesa-cassandra.
2. On running ingest via following above link, its creating 4 tables (mycatalog_example_2dcsv_z2 , mycatalog_example_2dcsv_id, mycatalog_example_2dcsv_z3, mycatalog) , its different.

I have another 3 questions as below:-
1. Is there is any option so that we can simply do insert one row manually instead of doing ingestion via file?
2. How to read the data stored in cassandra table ? As select select is not showing data which we ingested.
3. Do we have any cassandra example in this tutorials repo?

Please suggest.

**Comment by elahrvivaz** [comment]
We have instructions on setting up the command-line tools here, although we don't cover the available commands:
http://www.geomesa.org/documentation/user/cassandra/install.html#setting-up-the-cassandra-command-line-tools
As you note, they have changed since 1.3.0.
I don't believe that we have any quickstarts for Cassandra, but all of our implementations use the GeoTools data store API. So you should be able to take e.g. the hbase quickstart, add the cassandra datastore as a pom dependency, replace the hbase connection parameters with cassandra ones, and go.
Using a data store directly will allow you to ingest data in any format, you just have to convert it to `SimpleFeature`s. You can query either through the datastore or through the `export` command-line method.
More documentation on connecting to a cassandra datastore here:
http://www.geomesa.org/documentation/user/cassandra/usage.html

**Comment by elahrvivaz** [comment]
GeoMesa provides a geotools data store implementation for cassandra. If you're not familiar with geotools, check that out as well. They have tutorials on how to use data stores to insert and query data.

**Comment by jnh5y** [comment]
@ajayaks we just created a GeoMesa C* tutorial in this PR.  I'm going to close this issue.  Feel free to re-open or create a new issue as other concerns come up.
